### ISSUE TITLE
Did you find a solution?

### ISSUE THREAD

**Issue by trevorgowing** [maciejwalkowiak/testcontainers-spring-rabbitmq-issue#1]
@maciejwalkowiak I came across your repo because I am having the same issue. I was just wondering if you ever found a solution to the problem?

Thanks.

**Comment by maciejwalkowiak** [comment]
It was discussed on Slack. Let me copy & paste message from @bsideup June 27th, 2017:

> Hi @maciej.walkowiak
> 
> Thanks for providing a demo!
> 
> First thing I spotted was doubled `@RunWith` on TestContainersIssueApplicationTests (you don’t have to put them on class if you extend from already annotated abstract test class), but it wasn’t a problem.
> 
> Quick workaround:
> ```diff --git a/src/test/java/com/example/demo/AbstractIntegrationTest.java b/src/test/java/com/example/demo/AbstractIntegrationTest.java
> index ca956e2..a6fb963 100644
> --- a/src/test/java/com/example/demo/AbstractIntegrationTest.java
> +++ b/src/test/java/com/example/demo/AbstractIntegrationTest.java
> @@ -15,9 +15,12 @@ import org.testcontainers.containers.GenericContainer;
>  @ContextConfiguration(initializers = AbstractIntegrationTest.Initializer.class)
>  public abstract class AbstractIntegrationTest {
>  
> -    @ClassRule
>      public static GenericContainer rabbit = new GenericContainer("rabbitmq:3.6.6-management").withExposedPorts(5672, 15672);
>  
> +    static {
> +        rabbit.start();
> +    }
> +
> ```
> (edited)
> I’ll try to find why ClassRule is being stopped before Spring closes the context (sounds more like a bug), but at least you can get rid of that errors with this small change for now :slightly_smiling_face:

I remember that it did work for me, but then I had another issue that I haven't had time in the end to resolve.

**Comment by bsideup** [comment]
Hi guys,

Actually, with `static {}` and TestContainers 1.6.0 it should just work :)

**Comment by trevorgowing** [comment]
Thanks @maciejwalkowiak and @bsideup. That did the trick.
